#!/bin/sh
#SBATCH --job-name=sac0
#SBATCH --partition debug
#SBATCH --time=02:00:00
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --begin=now

module load python/3.7
source activate /home/daep/s.berger/.conda/envs/cfd_sureli

export SLURM_UNBUFFEREDIO=1
#path='results/SAC/flatplate_2022-04-29_14-46-52'

python3 -u train SAC --appli='flatplate' > output_sac_${SLURM_JOB_ID}
#python3 -u test SAC --appli='flatplate' > output_sac_$SLURM_JOB_ID
