#--------------------------------------------------------------------
############################# RL config #############################
#--------------------------------------------------------------------
# only for DDPG, TD3 or SAC

#------------- parameters common to DDPG, TD3 and SAC ---------------
GAME : "flatplate"

MEMORY_CAPACITY : 500000        # for the Replay Memory
BATCH_SIZE : 64
GAMMA : 0.99                    # discount factor
TAU : 0.005                     # update parameter of the target network

ACTION_SIGMA : 0.0              # environment noise ([0 --> 0; 1 --> max_pitch])

MAX_EPISODES : 10               # number of training episodes
MAX_STEPS : 150                 # max steps per episode
PRE_FILL_EPISODES : 8           # number of pre-filling episodes

# saving and plotting parameters
FREQ_PLOT : 100                 # frequency at which plots are updated
FREQ_EVAL : 1                   # evaluation frequency
FREQ_SAVE : 100                 # frequency at which the models are saved


#----- parameters common to DDPG, TD3 and SAC for LaBER and PER -----
#--- This version of the code does not allow to run PER nor LaBER ---
LaBER : False                   # if set to true LaBER is applied
LaBER_SLEEK : False             # if set to True LaBER sleek otherwise classical LaBER
M : 4                           # size reduction from large to mini-batch
                                # if LaBER is True, BATCH_SIZE defines the large batch size
PER : False                     # if set to true PER is applied
PER_OLD_PHILO : False           # if set to true PER_OLD_PHILO is applied


#-------------- parameters used only by DDPG and TD3 ----------------
HIDDEN_LAYERS : [32, 32]        # NN size
LEARNING_RATE_CRITIC : 0.001
LEARNING_RATE_ACTOR : 0.001

EXPLO_SIGMA : 0.05              # exploration noise


#------------------- parameters used only by TD3 --------------------
# next 2 parameters are set according to the founding paper
UPDATE_SIGMA : 0.2
UPDATE_CLIP : 0.5


#------------------- parameters used only by SAC --------------------
HIDDEN_VALUE_LAYERS : [32, 32]  # NN size
HIDDEN_Q_LAYERS : [32, 32]      # NN size
HIDDEN_PI_LAYERS : [32, 32]     # NN size

VALUE_LR : 0.001
SOFTQ_LR : 0.001
ACTOR_LR : 0.001

AUTO_ALPHA : True
ALPHA_LR : 0.001


#--------------------------------------------------------------------
############################ CFD config #############################
#--------------------------------------------------------------------
CFD_ITERATIONS : 1              # number of CFD iterations between two control iterations
DELTA_TIME : 0.00002            # time step

# initial position and velocity
XA : 0.0
YA : 0.0
UA : -10.0
VA : 0.0

# target position
BTYPE : "fixed"                 # target position type let it set to fixed
DISTANCE_RANGE : [0.01, 0.02]   # only used if BTYPE is "random"
ANGLE_RANGE : [-15., 15.]       # only used if BTYPE is "random"
XB : -0.02
YB : 0.002

# some parameters for the control problem
DENSITY_RATIO : 30.             # density ratio between the flatplate and the surrounding fluid
MAX_PITCHRATE : 500.            # maximum allowed pitch rate
REWARD_TYPE : "dense"           # choose between dense and sparse

# flat plate dimensions
CHORD : 0.01                    # flat plate chord
LENGTH : 0.01                   # flat plate length
THICKNESS : 0.0002              # flat plate thickness
